# Generated by Django 3.2.3 on 2021-06-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('fk_tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.tests')),
            ],
        ),
    ]
